// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SurveyAccessor.Context;

namespace SurveyAccessor.Migrations
{
    [DbContext(typeof(SurveysDbContext))]
    [Migration("20210718125616_add feature survey and total times taken")]
    partial class addfeaturesurveyandtotaltimestaken
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SurveyAccessor.Models.Survey", b =>
                {
                    b.Property<int>("SurveyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("FeaturedSurvey")
                        .HasColumnType("bit");

                    b.Property<string>("SurveyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SurveyQuestion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalTimesTaken")
                        .HasColumnType("int");

                    b.Property<int>("TotalVotes")
                        .HasColumnType("int");

                    b.HasKey("SurveyId");

                    b.ToTable("Surveys");
                });

            modelBuilder.Entity("SurveyAccessor.Models.SurveyOption", b =>
                {
                    b.Property<int>("SurveyOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Fk_SurveyId")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TotalVotes")
                        .HasColumnType("int");

                    b.HasKey("SurveyOptionId");

                    b.HasIndex("Fk_SurveyId");

                    b.ToTable("SurveyOptions");
                });

            modelBuilder.Entity("SurveyAccessor.Models.SurveyOption", b =>
                {
                    b.HasOne("SurveyAccessor.Models.Survey", "Survey")
                        .WithMany("SurveyOptions")
                        .HasForeignKey("Fk_SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("SurveyAccessor.Models.Survey", b =>
                {
                    b.Navigation("SurveyOptions");
                });
#pragma warning restore 612, 618
        }
    }
}
